let availablekeywords = [
  /* #1 */
  ' PERGUNTA: Leia o trecho abaixo Gerentes com responsabilidades sobre software assim como gerentes da maioria das áreas frequentemente estão sob pressão para manter os orçamentos evitar deslizes nos cronogramas e elevar a qualidade Como uma pessoa que está se afogando e se agarra à crença em um mito do software para aliviar a pressão mesmo que temporariamente Fonte PRESSMAN, Roger S MAXIM, Bruce R Engenharia de Software Uma Abordagem Profissional 8 ed Porto Alegre Amgh 2016 p 23Considerando essas informações e o conteúdo estudado, é possível afirmar que o trecho acima está relacionado ao: RESPOSTA CORRETA: MITO DE GERENCIAMENTO.',
  /* #2 */
  'PERGUNTA:  Leia o trecho a seguir: “O SWEBOK é recomendado para diversos tipos de público, em todo o mundo, com o objetivo de ajudar organizações a terem uma visão consistente da Engenharia de Software. É endereçado a gerentes, engenheiros de software, às sociedades profissionais, estudantes, professores e instrutores desta área de conhecimento.” Fonte: TORRES, André Luís de Lucena. Uma introdução ao SWEBOK. Disponível em: http://www.cin.ufpe.br/~processos/TAES3/Livro/00-LIVRO/11-SWEBOK-v8_CORRIGIDO_Versao_Final_OK.pdf. Acesso em: 25 abr. 2019. O trecho acima retrata as funcionalidades do SWEBOK. A partir dessas informações e do conteúdo estudado sobre o tema, pode-se concluir que o objetivo do SWEBOK é: RESPOSTA CORRETA: AUXILIAR AS EMPRESAS A OBSERVAREM DE MANEIRA MAIS AMPLA A ENGENHARIA DE SOFTWARE COMO UM TODO',
  /* #3 */
  'PERGUNTA: Leia o trecho a seguir: “O modelo clássico foi provavelmente a primeira metodologia publicada de desenvolvimento de software. Este modelo estabelece uma sequência de etapas. Cada etapa tem associada ao seu término uma documentação que deve ser aprovada para que a etapa posterior possa ter início.” Fonte: KOS CIANSKI, André; SOARES, Michel dos Santos. Qualidade de software: Aprenda as metodologias e técnicas mais modernas para o desenvolvimento do software. 2. ed. São Paulo: Novatec, 2007, p. 191.Considerando as informações apresentadas e o conteúdo estudado, é possível afirmar que o Modelo em Cascata está subdivido sequencialmente nas seguintes tarefas: RESPOSTA CORRETA: ANÁLISE E DEFINIÇÃO DOS REQUISITOS; PROJETO DE SISTEMA DE SOFTWARE; IMPLEMENTAÇÃO E TESTE UNITÁRIO; INTEGRAÇÃO E TESTE DE SISTEMA; E OPERAÇÃO E MANUTENÇÃO.',
   /* #4 */
  'PERGUNTA: Leia o trecho a seguir: “Nos anos 60, a expressão ‘crise de software’ começou a ser utilizada para denominar o conjunto de problemas encontrados no processo de desenvolvimento de software. Entretanto, mesmo com o surgimento da engenharia de software, muitos desses problemas persistiram e são recorrentes até os dias atuais”.Fonte: CABRAL, Ademilson Angelo; SILVA, Diego Bezerra da; SOUZA, Alan Pinheiro de. A problemática do desenvolvimento de software: crise ou calamidade crônica? Disponível em: http://revistaconexao.aems.edu.br/wp-content/plugins/download-attachments/includes/download.php?id=1614. Acesso em: 23 mar. 2019. Com base nessas informações e no conteúdo estudado, é possível verificar que os problemas relacionados à produção de software ainda não estão plenamente solucionados. Uma das situações que explicam as causas de a crise de software perdurar até os dias atuais está relacionado ao(s): RESPOSTA CORRETA: PROCESSO DE MATURAÇÃO NA FORMAÇÃO PROFISSIONAL SE ENCONTRAR EM ANDAMENTO.',
  /* #5 */
  'PERGUNTA: “Uma forma de utilizar o modelo cascata é quando precisamos fazer adaptações ou aperfeiçoamentos em um sistema já existente. Por exemplo, quando temos um sistema já pronto e precisamos fazer uma adaptação porque alguma lei governamental foi alterada ou criada”. Fonte: DEVMEDIA. Introdução ao Modelo Cascata. Disponível em: https://www.devmedia.com.br/introducao-ao-modelo-cascata/29843. Acesso em 31 mar. 2019. O trecho acima trata de uma das utilizações do método cascata. Baseado no conteúdo e no trecho citado, podemos afirmar que o modelo Cascata também se caracteriza por: RESPOSTA CORRETA: SER UM MODELO QUE SE ORIGINA DOS PROCESSOS MAIS GENERALISTAS DA ENGENHARIA DE SISTEMAS E PELO ENCADEAMENTO EXISTENTE ENTRE AS ETAPAS DO PROCESSO.',
  /* #6 */
  'PERGUNTA: Leia o trecho a seguir: “De fato, em meados de 1965 o termo crise de software não havia sido usado, isto ocorreu durante a década de 1970 quando as dificuldades relacionadas ao desenvolvimento do software começaram a ser mais graves [...]”. Fonte: MANZANO, Augusto. A engenharia de software, a qualidade final do software e o papel do profissional de desenvolvimento. Disponível em: https://www.revista-programar.info/artigos/a-engenharia-de-software-a-qualidade-final-do-software-e-o-papel-do-profissional-de-desenvolvimento/. Acesso em: 23 mar. 2019. O trecho acima trata da linha evolutiva do software até a sua crise. Baseado no conteúdo e no trecho citado, sabe-se que surgiram, neste período, as novas linguagens de programação. Esse período teve durabilidade até: RESPOSTA CORRETA: O ANO DE 1975, QUANDO O CRESCIMENTO DOS SISTEMAS BASEADOS EM COMPUTADORES SE DEU AO MESMO TEMPO EM QUE A MANUTENÇÃO FOI SE TORNANDO IMPOSSIVEL.',
  /* #7 */
  'PERGUNTA: Leia o trecho a seguir: “[...] baseado na ideia de desenvolver uma implementação inicial, expô-la aos comentários dos usuários e continuar por meio da criação de várias versões até que um sistema adequado seja desenvolvido. Atividades de especificação, desenvolvimento e validação são intercaladas, e não separadas, com rápido feedback entre todas as atividades.” Fonte: SOMMERVILLE, Ian. Engenharia de Software / Ian Sommerville. 9. ed. São Paulo: Pearson Prentice Hall, 2011, p. 23. A partir dessas informações e do conteúdo estudado, pode-se concluir que o trecho abordado se refere à aplicação do modelo: RESPOSTA CORRETA: DESENVOLVIMENTO INCREMENTAL.',
  /* #8 */
  'PERGUNTA: Leia o excerto abaixo: “A crise de software foi uma decorrência da imaturidade do mercado e dos profissionais da computação da época, pois vinha de um período em que o desenvolvimento do software não exigia requisitos e configurações complexas". Fonte: MANZANO, Augusto. A engenharia de software, a qualidade final do software e o papel do profissional de desenvolvimento. Disponível em: https://www.revista-programar.info/artigos/a-engenharia-de-software-a-qualidade-final-do-software-e-o-papel-do-profissional-de-desenvolvimento/. Acesso em: 23 mar. 2019.Esse trecho refere-se à motivação principal para a crise tecnológica ocorrida entre meados dos anos 1960 e os anos 1970. A partir dessas informações e do conteúdo estudado a respeito, podemos afirmar que a Crise de Software estava diretamente ligada ao: RESPOSTA CORRETA: MODELO DE TRABALHO EM EQUIPE QUE ERA PRATICADO, POIS, ALÉM DO FUNCIONAMENTO INCORRETO DO SISTEMA HAVIA UM AMBIENTE DE INCERTEZAS QUANTO A QUANTIDADE DE SOFTWARES E AS POSSÍVEIS DEMANDAS FUTURAS.',
  /* #9 */
  'PERGUNTA:  Leia o trecho a seguir: “Mitos que ainda sobrevivem em um determinado grupo, que atua na área, tem resistido por mais de 60 anos de cultura de programação. Durante os seus primórdios, a programação era vista como uma forma de arte. Hábitos e atitudes antigos são difíceis de perder.” Fonte: PRESSMAN, Roger S; MAXIM, Bruce R. Engenharia de Software: Uma Abordagem Profissional. 8 ed. Porto Alegre: Amgh. 2016, p. 23. Considerando essas informações e o conteúdo estudado, é possível afirmar que o trecho acima está relacionado ao: RESPOSTA CORRETA:  MITO DO PROFISSIONAL.',
  /* #10 */
  'PERGUNTA: Leia o trecho abaixo: “O solicitante do software computacional pode ser uma pessoa da mesa do lado. [...] Em muitos casos, acredita em mitos sobre software porque gerentes e profissionais da área pouco fazem para corrigir falsas informações. Mitos conduzem às falsas expectativas e, em uma última instância, à insatisfação com o desenvolvedor.” Fonte: PRESSMAN, Roger S; MAXIM, Bruce R. Engenharia de Software: Uma Abordagem Profissional. 8 ed. Porto Alegre: Amgh. 2016, p. 23. Considerando essas informações e o conteúdo estudado, é possível afirmar que o trecho acima está relacionado ao: RESPOSTA CORRETA: MITO DOS CLIENTES',
  /* #UNIDADE2 */

  /* #11 */
  'PERGUNTA: Leia o trecho a seguir: “É um artefato criado quando uma descrição detalhada de todos os aspectos do software ser construído deve ser especificado antes do projeto começar. É importante lembra que uma SRS formal nem sempre é por escrito. Na verdade, há ocasiões em que os esforços gastos em uma SRS talvez fossem mais bem aproveitados em outras atividades da engenharia de software”. Fonte: PRESSMAN, R. S.; MAXIM, B. R. Engenharia de Software: Uma Abordagem Profissional. 8 ed. Porto Alegre: Amgh. 2016, p. 136. A partir dessas informações e do conteúdo estudado, o trecho acima refere-se ao conceito de: RESPOSTA CORRETA: ESPECIFICAÇÃO DE SOFTWARE.',
  /* #12 */
  'PERGUNTA: “Extreme Programming (XP) é uma metodologia de desenvolvimento de software, nascida nos Estados Unidos ao final da década de 90. Vem fazendo sucesso em diversos países, por ajudar a criar sistemas de melhor qualidade, que são produzidos em menos tempo e de forma mais econômica que o habitual.” Fonte: EXTREME programming. DesenvolvimentoÁgil.com.br, [s.d.]. Disponível em: http://www.desenvolvimentoagil.com.br/xp/. Acesso em: 31 mar. 2019. O trecho acima trata da origem do método Extreme Programming e suas características. A partir dessas informações e do conteúdo estudado a respeito do Extreme Programming, é possível afirmar que os seus requisitos acontecem em forma de cenários, cuja implementação: RESPOSTA CORRETA: OCORRE DE MANEIRA DIRETA A UMA SÉRIE DE ATIVIDADES EM QUE OS PROGRAMADORES DESENVOLVERÃO TESTES PARA CADA UMA DELAS, NA FASE ANTERIOR Á ESCRITURA DO CÓDIGO.',
  /* #13 */
  'PERGUNTA:“A aplicação de Lean Software Development pode ajudar equipes de desenvolvimento de software a atingirem maior nível de maturidade em termos de qualidade e velocidade, entendendo e estudando seu processo atual, e trabalhando constantemente na identificação e eliminação de desperdícios.” Fonte: ANDRÉ. Lean Software Development: Java Magazine 81. Devmedia, 2010. Disponível em: https://www.devmedia.com.br/lean-software-development-java-magazine-81/17442. Acesso em: 31 mar. 2019. O trecho acima trata das funcionalidades da aplicação do Lean Software Development. A partir dessas informações e do conteúdo estudado a respeito dos processos de desenvolvimento de produtos, o conceito que está relacionado à criação e execução do produto pode ser denominado como: RESPOSTA CORRETA: LINHA DETERMINÍSTICA.',
  /* #14 */
  'PERGUNTA: “Scrum é uma metodologia ágil para gestão e planejamento de projetos de software. No Scrum, os projetos são divididos em ciclos (tipicamente mensais) chamados de Sprints. O Sprint representa um Time Box dentro do qual um conjunto de atividades deve ser executado.” Fonte:. SCRUM. DesenvolvimentoAgil.com.br, [s.d.]. Disponível em: https://www.desenvolvimentoagil.com.br/scrum/. Acesso em: 31 mar. 2019. O trecho aponta as características do método Scrum e suas funcionalidades. A partir dessas informações e do conteúdo estudado, pode-se concluir que a abordagem Scrum apresenta-se em três fases, dispostas sequencialmente como: RESPOSTA CORRETA: PLANJAMENTO GERAL, CICLOS DE SPRINT, ENCERRAMENTO DO PROJETO.',
  /* #15 */
  'PERGUNTA: “Em uma abordagem dirigida a planos, acontecem iterações no ambiente de atividades com documentos formais que são utilizados para estabelecer a comunicação entre os estágios do processo.” Fonte: PORTAL EDUCAÇÃO. Metodologias de desenvolvimento ágil de softwares. Disponível em: http://introduceti.com.br/blog/descubra-o-que-sao-os-metodos-ageis-e-sua-aplicacao-alem-da-ti/. Acesso em: 31 mar 2019. O trecho acima estabelece a utilização dos métodos ágeis dirigido a planos. A partir dessas informações e do conteúdo estudado, a abordagem dirigida a planos tem por objetivo: RESPOSTA CORRETA: IDENTIFICAR ETAPAS DIFERENTES DO PROCESSO DE SOFTWARE, EM QUE AS SAÍDAS ESTAO RELACIONADA A CADA ETAPA.',
  /* #16 */
  'PERGUNTA: “As metodologias ágeis surgiram nos últimos anos como uma alternativa aos métodos tradicionais de gestão de projetos de TI. Por exemplo SCRUM, XP, Lean etc. Elas são conhecidas por sua maior flexibilidade, capacidade de se adaptarem a mudanças no ambiente de trabalho e ciclos com duração reduzida.” Fonte: MOREIRA, E. Descubra o que são os métodos ágeis e sua aplicação além da TI. Introduce, 2017. Disponível em: https://blog.introduce.com.br/descubra-o-que-sao-os-metodos-ageis-e-sua-aplicacao-alem-da-ti/. Acesso em: 31 mar 2019. O trecho acima retrata os conceitos e funcionalidades dos métodos ágeis. A partir dessas informações e do conteúdo estudado, pode-se concluir que o diferencial dos Métodos Ágeis está na: RESPOSTA CORRETA: ENTREGA RÁPIDA DO PRODUTO AOS CLIENTES, QUE, AO RECEBEREM O SOFTWARE, PODEM OPINAR SOBRE MUDANÇAS POSTERIORES NO SISTEMA.',
  /* #17 */
  'PERGUNTA: “Gestores de TI interessados em otimizar a governança e em ampliar os resultados da área precisam estar atentos a essas inovações, e é relevante conhecer melhor o que é DevOps. Em essência, esse modelo aproxima o desenvolvimento da operação com o objetivo de simplificar processos, integrar áreas, alcançar maior qualidade nas entregas e reduzir o tempo de resposta ao cliente.” Fonte: DevOps. Gaea Consulting, [s.d.]. Disponível em: https://gaea.com.br/o-que-e-devops-conceito/. Acesso em 31 Mar. 2019. O trecho acima retrata a importância da aplicação do DevOps dentro das organizações. A partir dessas informações e do conteúdo estudado, é possível afirmar que o termo DevOps pode ser definido para: RESPOSTA CORRETA: UTILIZAÇÃO DE PROCESSOS AUTOMATIZADOS DIRECIONADOS A PRODUÇÃO MAIS VELOZ E MAIS ESTÁVEL DOS SERVIÇOS E APLICAÇÕES.',
  /* #18 */
  'PERGUNTA: “Uma forma de utilizar o modelo cascata é quando precisamos fazer adaptações ou aperfeiçoamentos em um sistema já existente. Por exemplo, quando temos um sistema já pronto e precisamos fazer uma adaptação porque alguma lei governamental foi alterada ou criada”. Fonte: HIGOR. Introdução ao Modelo Cascata. Devmedia, 2013. Disponível em: https://www.devmedia.com.br/introducao-ao-modelo-cascata/29843. Acesso em 31 mar. 2019. O trecho acima trata de uma das utilizações do método cascata. Baseado no conteúdo e no trecho citado, podemos afirmar que o modelo Cascata também se caracteriza por: RESPOSTA CORRETA: SER UM MODELO QUE SE ORIGINA DE UMA ABORDAGEM SISTEMÁTICA SEQUENCIAL AO DESENVOLVIMENTO DE SOFTWARE.',
    /* #19 */
  'PERGUNTA: Leia o trecho a seguir: “[...] baseado na ideia de desenvolver uma implementação inicial, expô-la aos comentários dos usuários e continuar por meio da criação de várias versões até que um sistema adequado seja desenvolvido. Atividades de especificação, desenvolvimento e validação são intercaladas, e não separadas, com rápido feedback entre todas as atividades.” Fonte: SOMMERVILLE, I. Engenharia de Software. Tradução de Ivan Bosnic e Kalinka G. de O. Gonçalves. Revisão técnica de Kechi Hirama. 9. ed. São Paulo: Pearson Prentice Hall, 2011, p. 23. A partir dessas informações e do conteúdo estudado, pode-se concluir que o trecho abordado se refere à aplicação do modelo:',
  'how to create a website RESPOSTA CORRETA: DE DESENVOLVIMENTO INCREMENTAL.',
  /* #20 */
  'PERGUNTA:  “Metodologia de desenvolvimento ágil é uma forma de construir software que possibilita obter as vantagens do sistema antes de ele estar pronto. Também encoraja os desenvolvedores a se aprimorarem constantemente. São utilizadas para agilizar o trabalho dos desenvolvedores e gerar melhoria contínua para os processos.” Fonte: METODOLOGIAS ágeis de desenvolvimento de software: saiba mais sobre o assunto. Cronapp Blog, 2019. Disponível em: https://blog.cronapp.io/metodologias-ageis-de-desenvolvimento-de-software/. Acesso em: 31 mar. 2019. Considerando as informações apresentadas e os conteúdos estudados, é possível afirmar que os processos de desenvolvimento rápido de software objetivam: RESPOSTA CORRETA: DESENVOLVER SOFTWARES ÚTEIS AO MERCADO QUE SEJAM PRODUZIDOS ENVOLVENDO UM CONJUNTO UM CONJUNTO DE INCREMENTOS QUE INCLUAM UMA NOVA FUNCIONALIDADE DO SISTEMA.',
  /* #UNIDADE 3 */

  /* #21 */
  'PERGUNTA: Leio o trecho a seguir: “A norma ISO/IEC 12207 estabelece uma arquitetura de alto nível do ciclo de vida de software que é construída a partir de um conjunto de processos e seus inter-relacionamentos”.  Fonte: MICREIROS.COM. Norma NBR ISSO/IEC 12207. Disponível em: http://micreiros.com/norma-nbr-isoiec-12207/. Acesso em: 13 abr. 2019. Esse trecho trata de uma das funções da ISO IEC 12207 no ciclo de vida do software. Assim, considerando as informações apresentadas e os conteúdos estudados, analise os processos primários realizados pela ISO/IEC 12207 e associe-os com suas respectivas características: 1. Fundamentais 2. Suporte 3. Organizacionais ( ) Esse processo ocorre através do contrato existente entre o fornecedor e adquirente do software. ( ) São utilizadas por uma empresa para definir e aplicar uma estrutura formada pelos processos. ( ) Refere-se ao auxílio e à contribuição que o processo possibilita para a qualidade. Agora, assinale a alternativa que apresenta a sequência correta: RESPOSTA CORRETA: 1,3,2.',
  /* #22 */
  'PERGUNTA: Leia o texto a seguir: “O MPS.BR (Melhoria de Processo de Software Brasileiro) é um modelo de maturidade desenvolvido por consórcio de empresas, com foco principal de atender aos micros, pequenas e médias empresas de software brasileiras, que necessitam melhorar seu processo de desenvolvimento de software.” Fonte: PERUCCI, C. C.; CAMPOS, F. C. de. Técnicas de qualidade aplicadas em Software: um estudo bibliométrico. Revista de Ciência e Tecnologia, v. 19, n. 38, p. 5-15. Disponível em: <https://www.metodista.br/revistas/revistas-unimep/index.php/cienciatecnologia/article/view/3091>. Acesso em 13 abr. 2019. p. 7. O trecho acima traz a definição do MPS.BR. A partir dessas informações e do conteúdo estudado, é possível visualizar que o modelo de Referência (MR-MPS) possui três guias. São elas: RESPOSTA CORRETA: GUIA GERAL, GUIA DE AQUISIÇÃO, GUIA DE IMPLEMENTAÇÃO.',
  /* #23 */
  'PERGUNTA: Leia o trecho a seguir: “Para ajudar nessa questão, a International Organization Standardization – ISO e a International Electrotechnical Comission – IEC, que são organismos normalizadores com importância internacional reconhecida no setor de software, se uniram para editar normas internacionais conjuntas. A norma internacional ISO/IEC, define qualidade de software como a totalidade de características de um produto de software que lhe confere a capacidade de satisfazer necessidades explícitas e implícitas”.Fonte: DEVEMEDIA. Qualidade de Software. Disponível em: https://www.devmedia.com.br/qualidade-de-software/9408. Acesso em: 12 abr. 2019. O trecho trata das normas internacionais de padronização de software e o critério de qualidade adotado. Considerando essas informações e o conteúdo estudado, é possível afirmar que mesmo com a evolução na quantidade de softwares disponíveis, o principal problema encontrado no desenvolvimento do software consiste em: RESPOSTA CORRETA: FALTA DE PADRONIZAÇÃO DO SOFTWARE.',
  /* #24 */
  'PERGUNTA: Leia o texto a seguir: “Provê informações sobre conceitos de avaliação de processo e seu uso em dois contextos, o de melhoria de processo e o de determinação de capacidade de processo. Ela descreve como as partes deste conjunto de normas se integram e provê orientações para seleção e uso”. Fonte: ABNT. Código 15504. Disponível em: https://www.abntcatalogo.com.br/curs.aspx?ID=63. Acesso em: 12 abr. 2019. O trecho refere-se a uma das características do histórico da norma ISO/IEC 15504. Assim, considerando as informações apresentadas e os conteúdos estudados, é possível definir a ISO/IEC 15504 como: RESPOSTA CORRETA: UM MODELO DE REFERENCIA CRIADO A PARTIR DE UM FRAMEWORK PARA ANALISAR PROCESSOS DA ÁREA DE ENGENHARIA DE SOFTWARE.',
  /* #25 */
  'PERGUNTA: Leia o excerto a seguir: “Em um ambiente no qual as entregas são rápidas e o produto é tratado de maneira mais dinâmica do que nunca, dessa forma, os profissionais de testes precisam garantir que, além do produto ser entregue com qualidade, que todo o processo de desenvolvimento siga tanto os critérios de SQA (Software Quality Assurance) como de Agile”. Fonte: IT FORUM 365. O perfil multidisciplinar do analista de teste. Disponível em: https://itforum365.com.br/o-perfil-multidisciplinar-do-analista-de-testes/. Acesso em: 12 abr. 2019. O trecho acima trata dos critérios de qualidade e rapidez na entrega adotada pelo SQA. A partir dessas informações e do conteúdo estudado, é possível afirmar que a mensuração, uma das fases da atividade SQA, é utilizada com a finalidade de: RESPOSTA CORRETA: ACOMPANHAR A QUALIDADE DE SOFTWARE E AVALIAR OS EFEITOS DAS ALTERAÇÕES NA METODOLOGIA E NOS PROCEDIMENTOS.',
  /* #26 */
  'PERGUNTA: Leia o trecho a seguir: “Um processo representa, dentro da área de software, um conjunto de atividades cujo objetivo é atingir uma meta previamente estipulada. Já por capacidade e maturidade de um processo, deve-se ter a noção do grau de qualidade com o qual um processo atinge um resultado esperado.”Esse trecho trata da diferença conceitual entre maturidade e processo. A partir dessas informações e do conteúdo estudado, é possível definir que o objetivo da CMM é: RESPOSTA CORRETA: DIRECIONAR A EMPRESA, IMPLEMENTANDO E MELHORANDO DE FORMA CONTÍNUA O PROCESSO DE SOFTWARE.',
  /* #27 */
  'PERGUNTA: Leia o trecho a seguir:“Entender a base de código e avaliar a qualidade do software é essencial para simplificar a complexidade e estabelecer uma linha de base para os esforços de modernização, manutenção e transformação.” Fonte: VERON, Frederic. 10 coisas que os CIOs precisam saber sobre seu software. Disponível em: <https://cio.com.br/10-coisas-que-os-cios-precisam-saber-sobre-seu-software/>. Acesso em: 12 abr. 2019.Esse trecho refere-se à importância da análise da qualidade de software. A partir dessas informações e do conteúdo estudado, é possível afirmar que um dos aspectos relacionados ao gerenciamento de qualidade de software aplicado em sistemas é: RESPOSTA CORRETA: O NIVEL ORGANIZACIONAL, EM QUE O GERENCIAMENTO DE QUALIDADE SE DEDICA EM DEFINIR UM FRAMEWORK DE PROCESSOS ORGANIZACIONAIS E DE PADRÕES.',
  /* #28 */
  'PERGUNTA: Leia o trecho a seguir: “O problema decorre de uma falha na realização de uma verdadeira garantia de qualidade de software, diz Mark S. Kadrich, CISO provisório para o hospital comunitário Martin Luther King Jr., em Los Angeles. ‘Estive no setor tempo suficiente para saber que, se eu estou perdendo o sono por falha na tecnologia, estou na indústria errada’, diz ele. ‘Oitenta por cento do software é uma porcaria, enquanto vinte por cento é apenas uma besteira. Há muito pouco que pode ser considerado bem projetado’”.Fonte: TYNAN, Dan. Seis verdades difíceis de aceitar e aprender. Disponível em: https://cio.com.br/seis-verdades-dificeis-de-aceitar-e-aprender/. Acesso em: 12 abr. 2019. O trecho traz a opinião de um especialista abordando os problemas decorrentes da falta de garantia de software. Assim, considerando as informações apresentadas e os conteúdos estudados, o padrão sistemático e planejado de ações consiste na definição da: RESPOSTA CORRETA: GARANTIA DE QUALIDADE DE SOFTWARE (SQA)',
  /* #29 */
  'PERGUNTA: Leia o texto a seguir:“A ABNT NBR ISO 9001 é a versão brasileira da norma internacional ISO 9001 que estabelece requisitos para o Sistema de Gestão da Qualidade (SGQ) de uma organização, não significando, necessariamente, conformidade de produto às suas respectivas especificações. O objetivo da ABNT NBR ISO 9001 é lhe prover confiança de que o seu fornecedor poderá fornecer, de forma consistente e repetitiva, bens e serviços de acordo com o que você especificou.” Fonte: INMETRO. O que significa a ABNT NBR ISO 9001 para quem compra? Disponível em: http://www.inmetro.gov.br/qualidade/pdf/cb25docorient.pdf. Acesso em: 13 abr. 2019. p. 1. Assim, considerando as informações apresentadas e os conteúdos estudados, é possível afirmar que uma das vantagens do uso da norma ISO 9001 é: RESPOSTA CORRETA: ATENDER OS ATRIBUTOS LEGAIS E REGULAMENTARES , ALEM DA POSSIBILIDADE DE SE EXPANDIR MERCADOS. ',
  /* #30 */
  'PERGUNTA: Leia o excerto a seguir: “É importante medir a qualidade do software, mas é igualmente importante executar a atividade de forma correta. Essa ação é muito útil no desenvolvimento de software, mas, muitas vezes, é melhor não ter medição alguma do que contar com uma errada.” Fonte: SUBRAMANYAM, Jitendra. Como medir com eficiência a qualidade de software na sua empresa. Disponível em: https://computerworld.com.br/2014/05/13/como-medir-com-eficiencia-a-qualidade-de-software-na-sua-empresa/. Acesso em: 12 abr. 2019. O trecho acima cita a importância de o software ser executado de maneira correta para evitar problemas. Baseado no conteúdo e no trecho citado, a Garantia da Qualidade é aplicada ao longo do processo de Engenharia de Software e abrange: RESPOSTA CORRETA: AÇOES QUE VISAM ADEQUAR-SE AOS MODELOS DE DESENVOLVIMENTO DE SOFTWARE. ',
  /* #UNIDADE 4 */

  /* #31 */
  'PERGUNTA: Leia o trecho a seguir: Alguns casos de uso podem estar associados a vários atores, mas geralmente somente um deles é que indica o caso de uso, enquanto os outros fornecem ou extraem informações. O nome dado ao caso de uso deve destacar o valor que ele vai gerar para o usuário. Fonte: MARTINS, José Carlos Cordeiro. Gerenciando Projetos de Desenvolvimento de Software com PMI, RUP, UML. 4ª Edição. Rio de Janeiro: Brasport, 2007, O trecho acima trata da importância dos casos de uso. Assim, considerando essas informações e os conteúdos estudados sobre os fundamentos de teste de software, pode-se afirmar que os casos de teste são: RESPOSTA CORRETA: ESPECIFICAÇÕES PRESENTES NAS ENTRADAS DO TESTE E NA SAÍDA PREVISTA PELO SISTEMA.',
  /* #32 */
  'PERGUNTA: Leia o excerto a seguir: A gestão de qualidade pessoal tem como objetivo auxiliar o engenheiro de software a trabalhar de forma real e objetiva com os defeitos que ele próprio insere no programa. Estes níveis adicionam métodos para gestão da qualidade ao PSP. Fonte: REZENDE, D. A. Engenharia de software e sistemas de informação. 3. ed. Rio de Janeiro: Brasport, 2005. p. 148. Considerando essas informações e o conteúdo estudado sobre o processo de gestão de defeitos, pode-se concluir que essa modalidade de gestão: RESPOSTA CORRETA: APRESENTA UMA FORMA DE PROMOVER INTEGRAÇÃO ENTRE A EQUIPE DE DESENVOLVIMENTO E DE TESTES.',
  /* #33 */
  'PERGUNTA: Leia o excerto a seguir: Inteligência artificial (IA) e machine learning (ML) para o bem e para o mal – conforme o IDC, até o final do próximo ano pelo menos metade dos SOCs (Security Operating Centers) adotam ferramentas de automação e inteligência artificial. Os ganhos de produtividade, com agilidade e escala, são mandatórios, inclusive, porque o outro lado também conta com recursos para automatizar testes. Fonte: TERRA. A Expansão Digital e os desafios da cibersegurança em 2020. Terra, 15 jan. 2020. Disponível em: https://bit.ly/2RFKVWB. Acesso em: 20 jan. 2020.Considerando essas informações e o conteúdo estudado sobre as principais ferramentas de automação de testes, pode-se afirmar que o Robotium: RESPOSTA CORRETA: E COMPATIVEL COM APLICAÇOES NATIVAS OU HÍBRIDAS E PERMITE ESCRITA SIMPLIFICADA DA AUTOMAÇÃO DE TESTES DE CAIXA-PRETA.',
  /* #34 */
  'PERGUNTA: Leia o trecho a seguir: O Objetivo de teste de caixa-preta é avaliar a conformidade de um módulo, sem entrar em detalhes quanto à sua implementação. Embora sejam mais simples de realizar, requerem uma massa de dados muito bem estruturadas. Normalmente, os roteiros de testes são preparados antes da construção do sistema. Fonte: SAMPAIO, Cleuton. Guia de campo do bom programador: como desenvolver o software Java EE com qualidade. Rio de Janeiro: Brasport, 2012, p. 23. O trecho acima trata de um dos objetivos da caixa-preta de software. Considerando essas informações e o conteúdo estudado referente aos fundamentos do teste de software, pode-se afirmar que o teste de caixa-preta: RESPOSTA CORRETA: E FEITO DENTRO DAS INTERFACES DE UM SOFTWARE, LOCALIZA POSSIVEIS ERROS E É EMPREGADO PARA COMPROVAR QUE AS FUNÇOES ATRIBUIDAS SÃO OPERACIONAIS.',
  /* #35 */
  'PERGUNTA: Leia o excerto a seguir: “O teste de invasão é uma atividade recomendada para avaliar a estrutura tecnológica da informação de acordo com uma visão externa e interna. Além de avaliar a segurança da informação, esse serviço avalia a qualidade dos controles de SI implementados.” Fonte: MANOEL, S. S. Governança de Segurança da Informação: como criar oportunidades para o seu negócio. Rio de Janeiro: Brasport, 2014. p. 74. Considerando essas informações e do conteúdo estudado sobre os desafios e benefícios da automação de testes, pode-se afirmar que a segurança de informação é obtida: RESPOSTA CORRETA: POR MEIO DE TESTES AUTOMATIZADOS, QUE PERMITEM REALIZAR VERIFICAÇÕES CONSTANTES PARA EVITAR A PRESENÇA DE HACKERS DENTRO DE UM CÓDIGO FALHO.',
  /* #36 */
  'PERGUNTA: Leia o trecho a seguir: Para planejar o teste de software de forma adequada, devem ser coletadas as métricas durante o teste e fazer uso de modelos existentes de confiabilidade de software, de modo que possam ser estabelecidas diretrizes significativas para que a equipe saiba quando parar de testar. Fonte: MARTINS, José Carlos Cordeiro. Técnica para Gerenciamento de projetos de Software. Rio de Janeiro: Brasport. 2007, p. 15. O trecho apresentado trata das condições necessárias para planejar e executar testes. Assim, considerando essas informações e o conteúdo estudado sobre fundamentos de teste de software, analise as afirmativas a seguir. I. A atividade de teste aponta que as funções de software estão sendo realizadas, considerando as especificações definidas. II. Os dados extraídos no instante em que a atividade de teste surte algum efeito apontam um nível de confiabilidade e qualidade de software, indicando a ausência dos bugs. III. O teste está inserido no processo de verificação e validação (V&V), que analisa a capacidade do software em desenvolvimento de atender às suas especificações e de oferecer a funcionalidade esperada pelos usuários. IV. O processo de Verificação e Validação (V&V) inclui o gerenciamento de interfaces, que é responsável por avaliar e observar os atributos pertencentes ao sistema. Está correto apenas o que se afirma em: RESPOSTA CORRETA: I,III',
  /* #37 */
  'PERGUNTA: Leia o trecho a seguir: Um software precisa ser testado para descobrir erros que foram feitos durante o projeto e construção. Os testes são conduzidos através de uma estratégia, que integra os métodos de teste, o passo e o roteiro. A estratégia de restes deve ser planejada sob medida para cada projeto, considerando o tempo que será investido neste trabalho. Fonte: MARTINS, José Carlos Cordeiro. Técnica para Gerenciamento de projetos de Software. Rio de Janeiro: Brasport, 2007, p. 15. O trecho refere-se às funcionalidades de um teste de software. Considerando essas informações e o conteúdo estudado a respeito dos fundamentos de testes de software, pode-se afirmar que as atividades relacionadas aos testes de software visam, entre outros aspectos: RESPOSTA CORRETA: GARANTIR A QUALIDADE E SIMBOLIZAR A ANÁLISE RECENTE DA ESPECIFICAÇÃO, PROJEÇÃO E CODIFICAÇÃO.',
  /* #38 */
  'PERGUNTA: Leia o trecho a seguir: A realização de inspeções em sistemas incompletos não é custosa. Entretanto, se um sistema incompleto é testado, então testes que se adequem a essa situação devem ser criados, o que acrescenta um custo a mais no processo. Fonte: SANTOS, Luiz Diego Vidal; OLIVEIRA, Catuxe Varjão de Santana. Introdução à garantia de qualidade de software. [s.l]: Cia do Ebook, 2017, p. 16. O trecho acima traz aspectos relacionados ao uso da inspeção nos sistemas. Considerando essas informações e o conteúdo estudado sobre os fundamentos dos testes de software, pode-se afirmar que as inspeções: RESPOSTA CORRETA: NÃO SUBSTITUEM OS TESTES DE SOFTWARES TRADICIONAIS.',
  /* #39 */
  'PERGUNTA:',
  /* #40 */
  'PERGUNTA:',

  ];
  
  const resultsBox = document.querySelector(".result-box");
  const inputBox = document.getElementById("input-box");
  
  inputBox.onkeyup = function(){
    let result = [];
    let input = inputBox.value;
    if(input.length){
      result = availablekeywords.filter((keyword)=>{
       return keyword.toLowerCase().includes(input.toLowerCase());
      });
      console.log(result);
    }
    display(result);
  }
  
  function display(result){
    const content = result.map((list)=>{
      return "<li>" + list + "</li>";
    });
  
    resultsBox.innerHTML = "<ul>" + content.join('') + "</ul>";
  }

  function openModal(){
    const modal = document.getElementById('modal-container')
    modal.classList.add('mostrar')

    modal.addEventListener('click', (e) =>{
        if (e.target.id == 'modal-container' || e.target.id == "fechar"){
            modal.classList.remove('mostrar')
            localStorage.fechaModal = 'modal-container'
        }
    })
}